/*
 * this code auto generated by UnityToolExtender
 * DO NOT EDIT IT!!!
 */

using UnityEditor;

namespace Wing.Tools.Editor
{
    public static partial class __tools__
    {
        [MenuItem("Tools/note pad")]
        static void __1026190295()
        {
            ToolExtends.Run("Tools/note pad");
        }
        
        [MenuItem("Tools/cmd11")]
        static void __604536796()
        {
            ToolExtends.Run("Tools/cmd11");
        }
        
    }
}